# scrutinizer-ci.com configuration
imports:
  - php
filter:
  excluded_paths:
    - build/
    - tmp/
    - vendor/
    - tools/doctum-config.php
checks:
  php: true
tools:
  external_code_coverage:
    runs: 2 # php 8.x versions
    timeout: 480 # 8 min
build:
  image: default-bionic # Needed to make PHP 8.2 compile
  nodes:
    analysis:
      environment:
        php:
          version: 8.2.29 # vimeo/psalm needs a newer version
      dependencies:
        before:
          - sudo /home/scrutinizer/.phpenv/shims/php -f /usr/bin/composer.phar self-update --2
          - composer --version
          - composer install
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run
